apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
namespace: dev
images:
- name: gitops-webapp
  newTag: 671b80d196146bea1e6c884b19d4defe91a696f0
- name: registry.gitlab.com/thekvothe/gitops-webapp
  newTag: e47d40db061cbbabfc5b7685dec05f120699f851
