apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
namespace: dev
images:
- name: gitops-webapp
  newTag: 5ee602b9faac1751f5a534337c278812cbd5e4f7
- name: registry.gitlab.com/thekvothe/gitops-webapp
  newTag: e47d40db061cbbabfc5b7685dec05f120699f851
