apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
namespace: dev
images:
- name: gitops-webapp
  newTag: 1772b9e6da93d96259b5796dfd4bd3217ede18d3
- name: registry.gitlab.com/thekvothe/gitops-webapp
  newTag: e47d40db061cbbabfc5b7685dec05f120699f851
