apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
namespace: dev
images:
- name: gitops-webapp
  newTag: 19f9b251faee5e49e52201c92cb9bda523170df3
- name: registry.gitlab.com/thekvothe/gitops-webapp
  newTag: e47d40db061cbbabfc5b7685dec05f120699f851
